text_extensions   : ['css', 'js', 'md', 'html', 'erb']
output_dir        : output
index_filenames   : ['index.html']
enable_output_diff: false

prune:
  auto_prune: true
  exclude   : ['.git']

data_sources:
  -
    type                        : filesystem_unified
    items_root                  : /
    layouts_root                : /
    allow_periods_in_identifiers: false

minify     : true
title      : Yorick Peterse
base_url   : http://localhost:3000
feed_url   : http://localhost:3000/feed.xml
#base_url  : http://yorickpeterse.com
#feed_url  : http://yorickpeterse.com/articles/atom
author_name: Yorick Peterse
author_uri : http://yorickpeterse.com

deploy:
  default:
    kind: rsync
    dst : "stewie.yorickpeterse.com:/srv/http/yorickpeterse.com/public"
