#!/usr/bin/env bash

# Deploy hook that is executed after a set of commits is pushed to a
# production server.
source submodules/deployment/lib/deployment

app_dir   '/srv/http/yorickpeterse.com'
runit_dir "$HOME/service/yorickpeterse.com"

runit_service 'exec chpst -d 62914560 \
    bundle exec unicorn -E none -c config/unicorn.rb config.ru 2>&1'

runit_log_service "svlogd -tt $RUNIT_DIR/log 2>&1"

cd_app
install_gems
migrate_db
restart_app
