source 'https://rubygems.org'

gem 'haml', '~> 5.0'
gem 'kramdown', '~> 1.0'
gem 'middleman', '~> 4.3'
gem 'middleman-blog', '~> 4.0'
gem 'middleman-livereload', '~> 3.4'
gem 'middleman-s3_sync', '~> 4.0'
gem 'middleman-syntax', '~> 3.0'
gem 'rake', '~> 13.0'
